### ISSUE TITLE
Allow for greater reusability and custom storage solutions

### ISSUE THREAD

**Issue by weilbith** [lennart-k/rustical#5]
Hey 👋

First of all, thanks for the inspiring work here! I’m on and off into this topic for quite some time now. Your code looks nicely structured and pretty clean. Great job! 🙌

My personal intend is to provide a CardDAV (and later also CalDAV) endpoint to my own application as an extra feature. I would rather not have to deal with the whole WebDAV stuff and it’s extensions myself. Unfortunately there is not a big list of implementations to choose from. Especially not in Rust or as a library. So I’m more than happy to see your effort here. 🤩

Your goal seem to target a standalone server application binary. Though, you nicely structured everything into separated library crates. But to make it reusable for a case like mine above, another package would be necessary I think.
The `src/app.rs` does the dirty job to inject the dependencies and plug everything together. It would be this point where to provide custom implementations of the `store` traits (and user management).
So if this part could be extracted into (another?) library crate, this would be phenomenal! Your root application crate still has the responsibility for the configuration, to define the commands etc. 

What are your thoughts on this? Would you be willed to expose the underlying implementation as a library others can depend on? I would highly value it!

Looking forward to the exchange.

**Comment by lennart-k** [comment]
Hey, thanks for your interest :)

So the current state of the project is still that I'm often restructuring many things as I'm sill learning by doing and things might break often since I still don't actively use it and don't have any automated tests yet.
This however should change in the future and I hope to maybe have something usable by the end of the year, let's see if that works out :D
(It might be functional already but not with enough confidence.)

Right now I only have SQLite for calendar/addressbook storage and static user configuration in a toml file since for me adding more options would just mean maintaining more code I don't need.
However, everything's generic over storage implementations so adding a custom storage solution would be relatively easy.

Regarding embedding the project in other software I mostly try to keep that use case in mind and expose useful functions as needed. :)
But I don't think the `make_app` function would be that useful to expose.
When embedding this project into your own you'd probably have your own `actix_web` app and explicitly want to select which modules to include where. You'd also perhaps want to serve the services under some prefix but still have to keep the `.well-known` paths.
So since there's no complicated logic in that I think that's really a snippet one would just copy-paste and adjust. :D

That all being said if you are still willing to dabble around with rustical I do appreciate that but keep in mind that it's still in an experimental state and not even I am using it actively yet.

**Comment by weilbith** [comment]
What a fast reply! 😊

Thanks for sharing all these insights. Sounds absolutely reasonable. I'm excited where this project will go. Do you plan to do releases via GitHub? Always makes it easier to follow a project by subscribing to releases. But I guess it's still to early yet? Or can someone actually subscribe on Crates.io? 🤔

That makes absolutely sense. I'm not too familiar with `actix`. But that sounds about right. So you can much easier mix it into your own application endpoints without putting any strain on your libraries (like how to exclude the Frontend). That's great! I'll try that.

But am I right that your application is 100% dependent on`actix`? So it wouldn't be possible to use the CardDAV and CalDAV crates web framework agnostic, right? I know it must be tons of work to reimplement all the relevant web concepts for the *DAV specifications in an agnostic way. I know [dav-sever-rs](https://github.com/messense/dav-server-rs/tree/main/examples/) did that. But probably tedious. 
I guess you could still try to  mix the *DAV endpoints with endpoints of a different web framework if absolutely desired. Not sure how they would share a port/socket. 🤔

Thank you very much!

**Comment by lennart-k** [comment]
Yes, once the project is in a usable state I'll start publishing releases. Until then I'm still enjoying the freedom of being able to break things without thinking about migrations :D

Regarding actix or other frameworks, my main priority at the moment is to have some stable standalone binary to use, from there on it should be relatively doable to make it framework-agnostic, but that remains to be seen.
Maybe I'll even switch to axum at some point.

Right now I'm mainly working on replacing serde for the xml parsing since it's not really made for unstructured data and my current implementation is quite janky. :)
