### ISSUE TITLE
Easy issue list? Roadmap? Projects list?

### ISSUE THREAD

**Issue by TornaxO7** [lennart-k/rustical#6]
Hi!
May I ask if you could create something like [Github Project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) to see what steps have to be done and how hard they might be to maybe help you with the development?

I'm aware that you created a [Todolist in the README](https://github.com/lennart-k/rustical?tab=readme-ov-file#todo) but is this still up to date? Which ones are rather easy to do?

Just curious :eyes:

**Comment by lennart-k** [comment]
Hey, thanks for your interest in contributing.
I think right now the project is still at a stage where it's easier to do things myself instead of delegating them because there are still some large changes that make merging difficult and frustrating.
The Todolist in the README is what I currently use to track my progress but I'll probably switch to issues fairly soon. :)

**Comment by TornaxO7** [comment]
>  I think right now the project is still at a stage where it's easier to do things myself instead of delegating them because there are still some large changes that make merging difficult and frustrating.

Okeyokey.

Keep up the great work :+1:
